/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TrialInputArgs struct {
	TimeLength float64 `json:"time_length,omitempty"`
	Credit float64 `json:"credit,omitempty"`
	TimeUnitName string `json:"time_unit_name,omitempty"`
}
