/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CustomerPortalStripeCredential struct {
	ClientSecret string `json:"client_secret,omitempty"`
	PublishableKey string `json:"publishable_key,omitempty"`
	AccountId string `json:"account_id,omitempty"`
}
