/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AccountingCustomer struct {
	// ID of the customer in the target accounting platform
	AccountingCustomerId string `json:"accounting_customer_id,omitempty"`
}
