/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type RevenueRecognitionEntry struct {
	// The newly booked amount in this month (in cents).
	Booked int32 `json:"booked,omitempty"`
	// The month in which the revenue is booked and(or) recognized.
	Month time.Time `json:"month,omitempty"`
	// The change in deferred revenue this month (in cents).
	Deferred int32 `json:"deferred,omitempty"`
	// The change in recognized revenue this month (in cents).
	Recognized int32 `json:"recognized,omitempty"`
}
