/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type CreateSubscriptionArgs struct {
	PricePlanName string `json:"price_plan_name,omitempty"`
	// DEPRECATED - use discounts field
	DiscountOverride *AllOfCreateSubscriptionArgsDiscountOverride `json:"discount_override,omitempty"`
	EffectiveAt time.Time `json:"effective_at,omitempty"`
	PricePlanTag string `json:"price_plan_tag,omitempty"`
	AddOns []SubscriptionAddOnInput `json:"add_ons,omitempty"`
	Discounts []DiscountInputArgs `json:"discounts,omitempty"`
	TrialOverride *TrialInputArgs `json:"trial_override,omitempty"`
	CouponOverrideId int32 `json:"coupon_override_id,omitempty"`
	VendorId int32 `json:"vendor_id,omitempty"`
	PricePlanId int32 `json:"price_plan_id,omitempty"`
	CustomerId int32 `json:"customer_id,omitempty"`
	CouponOverrideName string `json:"coupon_override_name,omitempty"`
	LimitsOverride []LimitInputArgs `json:"limits_override,omitempty"`
	FeaturesOverride []FeatureInputArgs `json:"features_override,omitempty"`
	AlignToCalendar bool `json:"align_to_calendar,omitempty"`
}
