/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type UpdateCustomerArgs struct {
	Tags []string `json:"tags,omitempty"`
	ContactInfo *ContactInfoInputArgs `json:"contact_info,omitempty"`
	VendorId int32 `json:"vendor_id,omitempty"`
	MeasurementMappings []CustomerMeasurementMappingInputArgs `json:"measurement_mappings,omitempty"`
	Name string `json:"name,omitempty"`
	DisplayName string `json:"display_name,omitempty"`
	CreatedAt time.Time `json:"created_at,omitempty"`
}
