/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CustomerPortalPaymentMethod struct {
	// Info about the customer's card, if that is their payment method.
	CardInfo *AllOfCustomerPortalPaymentMethodCardInfo `json:"card_info,omitempty"`
	// Type of payment method for the customer.
	PaymentMethodType string `json:"payment_method_type,omitempty"`
	// Info about the customer's US bank account, if that is their payment method.
	BankAccountInfo *AllOfCustomerPortalPaymentMethodBankAccountInfo `json:"bank_account_info,omitempty"`
}
