/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AddOnInputArgs struct {
	// Whether this add on can only be used & charged once.
	SingleUse bool `json:"single_use,omitempty"`
	Limit int32 `json:"limit,omitempty"`
	Feature *FeatureInputArgs `json:"feature"`
	QuantityEnabled bool `json:"quantity_enabled,omitempty"`
	// This field indicates whether or not we should cut an invoice immediately upon attaching this add on to a price plan.
	ImmediatelyCharge bool `json:"immediately_charge,omitempty"`
	Price int32 `json:"price,omitempty"`
}
