/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
type Customer struct {
	// Unique name identifier of a customer
	Name string `json:"name"`
	DisplayName string `json:"display_name,omitempty"`
	ContactInfo *AllOfCustomerContactInfo `json:"contact_info,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
	MeasurementMappings []map[string]string `json:"measurement_mappings,omitempty"`
	Tags []CustomerTag `json:"tags,omitempty"`
}
