/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UpdateVendorArgs struct {
	ContactInfo *ContactInfoInputArgs `json:"contact_info,omitempty"`
	VendorId int32 `json:"vendor_id,omitempty"`
	DisplayName string `json:"display_name,omitempty"`
}
