/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type CreditLedger struct {
	// The time at which this credit balance change occurred.
	Timestamp time.Time `json:"timestamp,omitempty"`
	// The change in numer of credits
	Amount int32 `json:"amount,omitempty"`
	// Credit balance as of this change
	Balance float64 `json:"balance,omitempty"`
	Pending bool `json:"pending,omitempty"`
}
