/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UpdatePricePlanInPlaceArgs struct {
	Limits []LimitInputArgs `json:"limits,omitempty"`
	Description string `json:"description,omitempty"`
	Features []FeatureInputArgs `json:"features,omitempty"`
	DisplayName string `json:"display_name,omitempty"`
	// Custom invoice description for the base price line item.
	BasePriceDescription string `json:"base_price_description,omitempty"`
	AddOns []AddOnInputArgs `json:"add_ons,omitempty"`
	MeteredComponents []MeteredComponentInputArgs `json:"metered_components,omitempty"`
}
