/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MeterInputArgs struct {
	MeterType string `json:"meter_type,omitempty"`
	UnitName string `json:"unit_name,omitempty"`
	Description string `json:"description,omitempty"`
	VendorId int32 `json:"vendor_id,omitempty"`
	EventName string `json:"event_name,omitempty"`
	Name string `json:"name,omitempty"`
	DisplayName string `json:"display_name,omitempty"`
	IsIncremental bool `json:"is_incremental,omitempty"`
	ExpectedLabels []string `json:"expected_labels,omitempty"`
	PrimaryLabels []string `json:"primary_labels,omitempty"`
}
