/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Add-on specification
type AllOfSubscriptionAddOnAddOn struct {
	Feature *Feature `json:"feature,omitempty"`
	// Price of the add on
	Price float64 `json:"price"`
}
