/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AddOn struct {
	Feature *Feature `json:"feature"`
	// Price of the add on
	Price float64 `json:"price"`
	// If true, customer is just charged once in the first billing cycle.
	SingleUse bool `json:"single_use"`
	QuantityEnabled bool `json:"quantity_enabled"`
	// If true, immediately invoice the customer for this add on.
	ImmediatelyCharge bool `json:"immediately_charge,omitempty"`
	// The maximum number of add-ons that an end-customer can apply to their subscription.
	Limit int32 `json:"limit,omitempty"`
}
