/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Meter struct {
	// Unique name identifier
	Name string `json:"name"`
	// Name used for display in UI
	DisplayName string `json:"display_name,omitempty"`
	Description string `json:"description,omitempty"`
	// Whether measurement values are to be considered incremental (versus a running total)
	IsIncremental bool `json:"is_incremental,omitempty"`
	MeterType string `json:"meter_type,omitempty"`
	// The expected unit for the measurement values associated with this meter.
	UnitName string `json:"unit_name,omitempty"`
	ExpectedLabels []string `json:"expected_labels,omitempty"`
	PrimaryLabels []string `json:"primary_labels,omitempty"`
}
