/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Coupon struct {
	// Unique name identifier.
	Name string `json:"name"`
	// UI-friendly name used for data display. Defaults to `name`.
	DisplayName string `json:"display_name,omitempty"`
	// The time when the coupon will stop being effective one its applied.
	DurationLength int32 `json:"duration_length,omitempty"`
	// The unit time unit to apply to the specified duration length.
	DurationUnit string `json:"duration_unit,omitempty"`
	// ISO-8601 formatted timestamp that defines after what timestamp this coupon cannot be applied.
	ExpirationTime time.Time `json:"expiration_time,omitempty"`
	Frequency string `json:"frequency,omitempty"`
	// The maximum number of times this coupon can be used.
	MaxUses int32 `json:"max_uses,omitempty"`
	// Customer facing code that can be used to apply coupon.
	Code string `json:"code,omitempty"`
	DiscountType string `json:"discount_type,omitempty"`
	// The amount of discount to give based on discount_type
	DiscountAmount float64 `json:"discount_amount"`
	ExcludedCustomers []Customer1 `json:"excluded_customers,omitempty"`
	ExcludedPricePlans []PricePlan1 `json:"excluded_price_plans,omitempty"`
}
