/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CustomerPortalActiveSubscriptionInputArgs struct {
	PricePlanUuid string `json:"price_plan_uuid,omitempty"`
	AddOns []SubscriptionAddOnInput `json:"add_ons,omitempty"`
}
