/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type CouponInputArgs struct {
	VendorId int32 `json:"vendor_id,omitempty"`
	Name string `json:"name"`
	DisplayName string `json:"display_name,omitempty"`
	ExpirationTime time.Time `json:"expiration_time,omitempty"`
	Frequency string `json:"frequency"`
	DurationLength int32 `json:"duration_length,omitempty"`
	DurationUnit string `json:"duration_unit,omitempty"`
	MaxUses int32 `json:"max_uses,omitempty"`
	Code string `json:"code,omitempty"`
	ExcludedCustomers []string `json:"excluded_customers,omitempty"`
	ExcludedPricePlans []string `json:"excluded_price_plans,omitempty"`
	DiscountType string `json:"discount_type"`
	DiscountAmount float64 `json:"discount_amount"`
}
