/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Feature struct {
	Description string `json:"description,omitempty"`
	// Unique name of a feature
	Name string `json:"name"`
	DisplayName string `json:"display_name,omitempty"`
}
