/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type CustomerPortalInvoice struct {
	// Information related to the current status of this invoice.
	Status *AllOfCustomerPortalInvoiceStatus `json:"status,omitempty"`
	// Any discount credits applied to the invoice
	DiscountCredit int32 `json:"discount_credit,omitempty"`
	// Earliest start time of line items covered by the invoice
	MinItemStartTime time.Time `json:"min_item_start_time,omitempty"`
	// Url pointing to the pdf of this invoice.
	PdfUrl string `json:"pdf_url,omitempty"`
	// Latest end time of line items covered by the invoice
	MaxItemEndTime time.Time `json:"max_item_end_time,omitempty"`
	// Amount due before any credits are applied
	SubTotal int32 `json:"sub_total,omitempty"`
	// The date the invoice will be issued to the end customer or forwarded to the payment processor.
	IssueDate time.Time `json:"issue_date,omitempty"`
	// False if not paid yet
	IsPaid bool `json:"is_paid,omitempty"`
	DueDate time.Time `json:"due_date,omitempty"`
	Id string `json:"id,omitempty"`
	// [DEPRECATED] Start time of the cycle in which the invoice was generated
	StartTime time.Time `json:"start_time,omitempty"`
	LineItems []LineItems `json:"line_items,omitempty"`
	// Total amount due
	AmountDue int32 `json:"amount_due,omitempty"`
	// [DEPRECATED] End time of the cycle in which the invoice was generated
	EndTime time.Time `json:"end_time,omitempty"`
	// Tax amount applied to subtotal
	TaxAmount int32 `json:"tax_amount,omitempty"`
}
