/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ValidateCredentialsArgs struct {
	// Username of the Avalara account
	Username string `json:"username"`
	// True if using a Avalara sandbox account, False otherwise
	SandboxMode bool `json:"sandbox_mode"`
	// Password of the Avalara account
	Password string `json:"password"`
}
