/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CustomerPortalMeterLabelFilter struct {
	// The aggregate function to use for the meter.
	Aggregate string `json:"aggregate,omitempty"`
	// Name of the meter.
	MeterName string `json:"meter_name"`
	// Primary labels with keys and values
	LabelFilters []CustomerPortalLabelFilter `json:"label_filters,omitempty"`
	// The label key to group results by.
	LabelGroupBy string `json:"label_group_by,omitempty"`
}
