/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Measurement struct {
	// The raw value of the measurement
	Value float64 `json:"value"`
	// A set of key:value label pairs to supplement a measurement. Each meter defines its own set of primary and/or expected labels.
	Labels map[string]string `json:"labels,omitempty"`
	// All times are parsed as `ISO-8601` formatted, UTC-based timestamps
	Time time.Time `json:"time,omitempty"`
	// The unique name of the meter associated with this measurement
	MeterName string `json:"meter_name"`
	// Applies to incremental meters and resets the total current value to this new value.
	ResetTotal bool `json:"reset_total,omitempty"`
}
