/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LineItems struct {
	PriceInt int32 `json:"price_int,omitempty"`
	Description string `json:"description,omitempty"`
	QuantityUnit string `json:"quantity_unit,omitempty"`
	Name string `json:"name,omitempty"`
	Quantity float64 `json:"quantity,omitempty"`
	Price string `json:"price,omitempty"`
	Id string `json:"id,omitempty"`
	Metadata map[string]string `json:"metadata,omitempty"`
}
