/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PriceInputArgs struct {
	Cap float64 `json:"cap,omitempty"`
	Description string `json:"description,omitempty"`
	Price float64 `json:"price,omitempty"`
}
