/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RevenueBreakdown struct {
	TotalRevenue float64 `json:"total_revenue,omitempty"`
	LineItems []LineItems `json:"line_items,omitempty"`
}
