/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Vendor struct {
	// Unique name identifier of a Vendor
	Name string `json:"name"`
	DisplayName string `json:"display_name,omitempty"`
	ApiKey string `json:"api_key,omitempty"`
	ContactInfo *AllOfVendorContactInfo `json:"contact_info,omitempty"`
}
