/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BillingSettings struct {
	// Time length of the grace period between the end of a billing cycle and invoice generation. *NOTE*: The specified length is unitless. Unit is designated with the `invoice_grace_period_unit` field.
	InvoiceGracePeriodLength int32 `json:"invoice_grace_period_length,omitempty"`
	// Time length unit of the grace period between the end of a billing cycle and invoice generation. One of `minute`, `hour`, `day`.
	InvoiceGracePeriodUnit string `json:"invoice_grace_period_unit,omitempty"`
	// Time length of the grace period between the end of invoice generation and the actual charge. *NOTE*: The specified length is unitless. Unit is designated with the `payment_grace_period_unit` field.
	PaymentGracePeriodLength int32 `json:"payment_grace_period_length,omitempty"`
	// Time length unit of the grace period between the end of invoice generation and actual charge. One of `minute`, `hour`, `day`.
	PaymentGracePeriodUnit string `json:"payment_grace_period_unit,omitempty"`
	// Flag that controls whether or not invoices should be sent to customers.
	ShouldSendInvoiceToCustomers bool `json:"should_send_invoice_to_customers,omitempty"`
	CustomerInvoiceDetailLevel string `json:"customer_invoice_detail_level,omitempty"`
	// Flag that controls whether or not to charge the customer based on the invoice.
	ChargesEnabled bool `json:"charges_enabled,omitempty"`
}
