/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UpdateSubscriptionInPlaceArgs struct {
	CouponOverrideName string `json:"coupon_override_name,omitempty"`
	DiscountOverride *AllOfUpdateSubscriptionInPlaceArgsDiscountOverride `json:"discount_override,omitempty"`
	AddOns []SubscriptionAddOnInput `json:"add_ons,omitempty"`
}
