/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AddOnInputArgs struct {
	QuantityEnabled bool `json:"quantity_enabled,omitempty"`
	Feature *FeatureInputArgs `json:"feature,omitempty"`
	// Whether this add on can only be used & charged once
	SingleUse bool `json:"single_use,omitempty"`
	Limit int32 `json:"limit,omitempty"`
	Price int32 `json:"price,omitempty"`
}
