/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Webhook struct {
	// The url to send the webhooks to.
	Url string `json:"url"`
	// Unique string identifier representing this webhook configuration.
	Uuid string `json:"uuid,omitempty"`
	// Determines whether Octane will sign the outgoing webhook
	EnableSignature bool `json:"enable_signature"`
}
