/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AccruedRevenueLineItem struct {
	// Any extra metadata associated with the item.          Will include the labels for metered components and metered component minimum charges when applicable
	Metadata map[string]string `json:"metadata,omitempty"`
	// Accrued revenue for this line item in cents
	Revenue int32 `json:"revenue,omitempty"`
	// Type of item. One of: METERED_COMPONENT, BASE_PRICE, DISCOUNT, ADD_ON, MINIMUM_CHARGE, METERED_COMPONENT_MINIMUM_CHARGE
	ItemType string `json:"item_type,omitempty"`
	//          The identifier of the item being returned.          For metered component will be meter name,          for add_ons will be feature name,          for base price will be price plan name,         for minimum charge will be price plan name,         for metered component minimum charge will be meter name         
	ItemIdentifier string `json:"item_identifier,omitempty"`
}
