/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CustomerPortalMeterLabels struct {
	Key string `json:"key,omitempty"`
	// Primary label values associated with the key
	Values []string `json:"values,omitempty"`
}
