/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UpdateMeterArgs struct {
	Description string `json:"description,omitempty"`
	ExpectedLabels []string `json:"expected_labels,omitempty"`
	PrimaryLabels []string `json:"primary_labels,omitempty"`
	DisplayName string `json:"display_name,omitempty"`
}
