/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CustomerPortalLabelDisplayName struct {
	DisplayName string `json:"display_name,omitempty"`
	// The raw value of the label data
	Name string `json:"name,omitempty"`
}
