/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DeleteDiscountInputArgs struct {
	// External UUID representing the discount to be deleted.
	DiscountUuid string `json:"discount_uuid"`
}
