/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Limit struct {
	Feature *Feature `json:"feature,omitempty"`
	// Limit on feature
	Limit float64 `json:"limit"`
}
