/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CustomerPortalSettings struct {
	// Comma-separated list of names to filter visible price plans by.
	PricePlanNamesFilter string `json:"price_plan_names_filter,omitempty"`
	// Comma-separated list of tags to filter visible price plans by.
	PricePlanTagsFilter string `json:"price_plan_tags_filter,omitempty"`
}
