/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type UpdateSubscriptionArgs struct {
	PricePlanName string `json:"price_plan_name,omitempty"`
	DiscountOverride *DiscountInputArgs `json:"discount_override,omitempty"`
	CouponOverrideName string `json:"coupon_override_name,omitempty"`
	EffectiveAt time.Time `json:"effective_at,omitempty"`
	CouponOverrideId int32 `json:"coupon_override_id,omitempty"`
	CustomerId int32 `json:"customer_id,omitempty"`
	PricePlanId int32 `json:"price_plan_id,omitempty"`
	VendorId int32 `json:"vendor_id,omitempty"`
	PricePlanTag string `json:"price_plan_tag,omitempty"`
}
