/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type CreditGrant struct {
	// Number of credits granted
	Amount float64 `json:"amount,omitempty"`
	// The date at which this grant is effective
	EffectiveAt time.Time `json:"effective_at,omitempty"`
	// A unique identifier for this grant
	Uuid string `json:"uuid,omitempty"`
	// The date at which this grant expires
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// Name of the customer who received the grant
	CustomerName string `json:"customer_name,omitempty"`
	// The source of the grant.
	Source string `json:"source,omitempty"`
	// Optional description. This is only viewable internally
	Description string `json:"description,omitempty"`
	// Total price paid for the credits, in cents
	Price int32 `json:"price,omitempty"`
}
