/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// Information related to the current status of this invoice.
type AllOfCustomerPortalInvoiceStatus struct {
	// Time the invoice status was last updated.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	UpdateSource string `json:"update_source,omitempty"`
	// Creation time of this invoice status.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// The timestamp that the action will be performed at.
	PendingActionTime time.Time `json:"pending_action_time,omitempty"`
	Error_ string `json:"error,omitempty"`
	// The current processing state for this invoice.
	Status string `json:"status,omitempty"`
	// The current upcoming action associated with this invoice status, if any.
	Action string `json:"action,omitempty"`
}
