/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type BillingCycleDate struct {
	CycleStart time.Time `json:"cycle_start,omitempty"`
	CycleEnd time.Time `json:"cycle_end,omitempty"`
}
