/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MeteredComponent struct {
	// Unique name identifier
	MeterName string `json:"meter_name,omitempty"`
	PriceScheme *PriceScheme `json:"price_scheme,omitempty"`
	// Limit to set on the metered component.
	Limit float64 `json:"limit,omitempty"`
}
