/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type CreateCreditGrantArgs struct {
	// Number of credits to grant
	Amount float64 `json:"amount"`
	// The date at which the grant is effective
	EffectiveAt time.Time `json:"effective_at,omitempty"`
	// Total price paid for the credits. Defaults to $1 per credit if not specified
	Price int32 `json:"price,omitempty"`
	// The date at which this grant expires
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// Optional description
	Description string `json:"description,omitempty"`
	// Name of the customer receving the grant
	CustomerName string `json:"customer_name"`
}
