/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type RollApiKeyArgs struct {
	// The date at which this API key will expire. Will default to 7 days.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// The API key you want to roll.
	ApiKey string `json:"api_key"`
}
