/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// Customer's current active biling cycle.
type AllOfCustomerPortalActiveSubscriptionBillingCycle struct {
	CycleStart time.Time `json:"cycle_start"`
	CycleEnd time.Time `json:"cycle_end"`
}
