/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreateWebhookArgs struct {
	Url string `json:"url,omitempty"`
	EnableSignature bool `json:"enable_signature,omitempty"`
}
