/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Subscription struct {
	// Unique name identifier of a customer
	CustomerName string `json:"customer_name"`
	// Unique name indentifier of a price plan
	PricePlanName string `json:"price_plan_name"`
	// Optional discount override for the associated subscription.
	DiscountOverride *AllOfSubscriptionDiscountOverride `json:"discount_override,omitempty"`
	// Optional trial override for the associated subscription.
	TrialOverride *AllOfSubscriptionTrialOverride `json:"trial_override,omitempty"`
	// Optional base price override for the associated subscription.
	BasePriceOverride float64 `json:"base_price_override,omitempty"`
	// ISO-8601 formatted timestamp that defines when the subscription should take effect. If this field is omitted, the subscription is effective upon creation.
	EffectiveAt time.Time `json:"effective_at,omitempty"`
}
