/*
 * Octane API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UpdateVendorAvalaraSettingsArgs struct {
	// True if the documents generated in Avalara should be committed, false otherwise.
	CommitDocuments bool `json:"commit_documents,omitempty"`
	// The item description to use to represent all the lines on the Octane invoice.
	ItemDescription string `json:"item_description,omitempty"`
	// Enable/Disable the Avalara integration.
	EnableIntegration bool `json:"enable_integration,omitempty"`
	// The Avalara item code to use to represent all the line items on the Octane invoice.
	ItemCode string `json:"item_code,omitempty"`
	// True if enabling logging for Avalara calls, false otherwise.
	EnableLogging bool `json:"enable_logging,omitempty"`
	// The Avalara company code string to associate the Octane vendor with.
	CompanyCode string `json:"company_code,omitempty"`
	// he tax code to associate with the item that is representing the Octane invoice.
	TaxCode string `json:"tax_code,omitempty"`
}
